---
abstract: 'Minimalist exception hierarchy generator'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Exporter: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec::Functions: '0'
  List::Util: '0'
  Test::More: '0.96'
  lib: '0'
  version: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: failures
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  custom::failures:
    file: lib/custom/failures.pm
    version: '0.004'
  failure:
    file: lib/failures.pm
    version: '0.004'
  failures:
    file: lib/failures.pm
    version: '0.004'
requires:
  Carp: '0'
  Class::Tiny: '0'
  overload: '0'
  parent: '0'
  perl: '5.008001'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/dagolden/failures/issues
  homepage: https://github.com/dagolden/failures
  repository: https://github.com/dagolden/failures.git
version: '0.004'
x_authority: cpan:DAGOLDEN
x_contributors:
  - 'Michael Jemmeson <mjemmeson@cpan.org>'
